import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

# Grab directory for the app
basedir = os.path.abspath(os.path.dirname(__file__))

# Instanciate the app
app = Flask(__name__)

# Set up the database location
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///" + os.path.join(basedir, "data.sqlite")

# Don't track all modifications in the database
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False

# Instanciate the DB
db = SQLAlchemy(app)

# Build the model
class Puppy(db.Model):
	# Table name (with out it, Flask will create the table with the same name as the class)
	__tablename__ = "puppies"
	# Create table columns
	# Primary Key column. Unique ids for each puppy are autogenerated
	id = db.Column(db.Integer, primary_key = True)
	# Puppy name - a text
	name = db.Column(db.Text)
	# Puppy age (in years) - an integer
	age = db.Column(db.Integer)
	# Set what an instance of this class (ie, in this table) will have
	def __init__(self, name, age):
		self.name = name
		self.age = age
	def __repr__(self):
		# This is the string representation of a puppy in the model
		return f"Puppy {self.name} is {self.age} years old."
